// Automatically generated by the bundler tool from C:\Users\John\Desktop\Xbox Stuff\My Shit\2016 Softmod Kit\Source\Other\FontBundle\New Font\Segoe_UI_Semibold_10.rdf

#define Segoe_UI_Semibold_10_NUM_RESOURCES 2UL

#define Segoe_UI_Semibold_10_Font_OFFSET 0UL
#define Segoe_UI_Semibold_10_FontData_OFFSET 20UL
