// Generated by BreakPoint Software's Hex Workshop v4.10
//   http://www.hexworkshop.com
//   http://www.bpsoft.com
//
//  Source File: backdrop.bin
//         Time: 8/15/2004 10:37 PM
// Orig. Offset: 0 / 0x00000000
//       Length: 921656 / 0x000E1038   
unsigned char g_BackTex[921656] =
{
     
} ;
